#!/usr/bin/env node
/**
 * Builds supabase/seeds/liturgical_calendar.sql from EVENT_DEFINITIONS + computus.
 * Environment:
 *   LITURGICAL_YEAR_START (default 2000)
 *   LITURGICAL_YEAR_END   (default 2200)
 *   LITURGICAL_OUT        (default ../../supabase/seeds/liturgical_calendar.sql)
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  baptismOfTheLord,
  christTheKing,
  easterSundayUtc,
  holyFamily,
  utcToCivilDate,
  addDaysUtc,
} from './computus.mjs';
import { EVENT_DEFINITIONS } from './event-definitions.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

const YEAR_START = parseInt(process.env.LITURGICAL_YEAR_START || '2000', 10);
const YEAR_END = parseInt(process.env.LITURGICAL_YEAR_END || '2200', 10);
const OUT = process.env.LITURGICAL_OUT || join(__dirname, '../../supabase/seeds/liturgical_calendar.sql');

/** @param {string} s */
function sqlStr(s) {
  if (s == null) return "''";
  return `'${String(s).replace(/'/g, "''")}'`;
}

/** @param {import('./event-definitions.mjs').EventDef} e @param {number} year */
function resolveObservanceIso(e, year) {
  const s = e.schedule;
  switch (s.type) {
    case 'fixed': {
      const d = new Date(Date.UTC(year, s.month - 1, s.day));
      return utcToCivilDate(d).iso;
    }
    case 'easter_offset': {
      const easter = easterSundayUtc(year);
      const d = addDaysUtc(easter, s.offset);
      return utcToCivilDate(d).iso;
    }
    case 'baptism_lord':
      return utcToCivilDate(baptismOfTheLord(year)).iso;
    case 'christ_king':
      return utcToCivilDate(christTheKing(year)).iso;
    case 'holy_family':
      return utcToCivilDate(holyFamily(year)).iso;
    default:
      throw new Error(`Unknown schedule ${/** @type {any} */ (s).type}`);
  }
}

function buildEventInserts() {
  const rows = EVENT_DEFINITIONS.map(
    (e) =>
      `(${sqlStr(e.id)}, ${sqlStr(e.name)}, ${sqlStr(e.summary)}, ${sqlStr(e.description)}, ${sqlStr(e.rank)}::public.liturgical_rank, ${e.liturgical_color == null ? 'null' : sqlStr(e.liturgical_color)}, ${e.is_universal}, ${e.is_franciscan_specific}, ${sqlStr(e.role_titles)})`,
  );
  return `insert into public.liturgical_events (id, name, summary, description, rank, liturgical_color, is_universal, is_franciscan_specific, role_titles) values\n${rows.join(',\n')}\non conflict (id) do update set\n  name = excluded.name,\n  summary = excluded.summary,\n  description = excluded.description,\n  rank = excluded.rank,\n  liturgical_color = excluded.liturgical_color,\n  is_universal = excluded.is_universal,\n  is_franciscan_specific = excluded.is_franciscan_specific,\n  role_titles = excluded.role_titles;\n`;
}

function buildObservanceInserts() {
  /** @type {string[]} */
  const values = [];
  for (let year = YEAR_START; year <= YEAR_END; year++) {
    for (const e of EVENT_DEFINITIONS) {
      const iso = resolveObservanceIso(e, year);
      values.push(`(${sqlStr(e.id)}, '${iso}'::date)`);
    }
  }
  const batch = 400;
  const chunks = [];
  chunks.push(
    'truncate table public.liturgical_observances restart identity cascade;\n',
  );
  for (let i = 0; i < values.length; i += batch) {
    const slice = values.slice(i, i + batch);
    chunks.push(
      `insert into public.liturgical_observances (event_id, observance_date) values\n${slice.join(',\n')};\n`,
    );
  }
  return chunks.join('\n');
}

function main() {
  if (YEAR_END < YEAR_START) {
    console.error('LITURGICAL_YEAR_END must be >= LITURGICAL_YEAR_START');
    process.exit(1);
  }

  const header = `-- Generated by backend/scripts/liturgical/generate-seed.mjs
-- Years: ${YEAR_START}–${YEAR_END} (inclusive). Regenerate after editing event-definitions.mjs.
begin;
`;

  const footer = `commit;
`;

  const body = `${buildEventInserts()}\n${buildObservanceInserts()}`;
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, header + body + footer, 'utf8');

  const nObs = (YEAR_END - YEAR_START + 1) * EVENT_DEFINITIONS.length;
  console.log(`Wrote ${OUT}`);
  console.log(`Events: ${EVENT_DEFINITIONS.length}, observance rows: ${nObs}`);
}

main();
