-- Liturgical calendar: canonical events (saints/feasts) and dated observances.
-- Observances are generated for a year range by scripts/liturgical/generate-seed.mjs

do $$
begin
  if not exists (select 1 from pg_type where typname = 'liturgical_rank') then
    create type public.liturgical_rank as enum (
      'solemnity',
      'feast',
      'memorial',
      'optional_memorial',
      'commemoration'
    );
  end if;
end $$;

create table if not exists public.liturgical_events (
  id text primary key,
  name text not null check (length(trim(name)) > 0),
  summary text not null default '',
  description text not null default '',
  rank public.liturgical_rank not null,
  liturgical_color text,
  is_universal boolean not null default false,
  is_franciscan_specific boolean not null default false,
  role_titles text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.liturgical_observances (
  id uuid primary key default gen_random_uuid(),
  event_id text not null references public.liturgical_events (id) on delete cascade,
  observance_date date not null,
  civil_year smallint not null generated always as (extract(year from observance_date)::smallint) stored,
  sort_order smallint not null default 0,
  unique (event_id, observance_date)
);

create index if not exists idx_liturgical_observances_date on public.liturgical_observances (observance_date);
create index if not exists idx_liturgical_observances_event on public.liturgical_observances (event_id);
create index if not exists idx_liturgical_observances_year on public.liturgical_observances (civil_year);
create index if not exists idx_liturgical_events_universal on public.liturgical_events (is_universal);
create index if not exists idx_liturgical_events_franciscan on public.liturgical_events (is_franciscan_specific);

drop trigger if exists trg_liturgical_events_set_updated_at on public.liturgical_events;
create trigger trg_liturgical_events_set_updated_at
before update on public.liturgical_events
for each row execute function public.set_updated_at();

comment on table public.liturgical_events is
  'Master catalog of saints and liturgical celebrations; dates are materialized in liturgical_observances.';
comment on column public.liturgical_events.is_franciscan_specific is
  'True when the row is chiefly for Franciscan families (OFM/OSF/TOR/Third Order) in addition to or beyond the General Roman Calendar.';
comment on table public.liturgical_observances is
  'One row per event per calendar day (civil date); generated by backend/scripts/liturgical/generate-seed.mjs.';
